SENDGRID_PASSWORD: 
SENDGRID_USERNAME: 
DEVISE_SECRET_KEY: 
development:
  FACEBOOK_ID: 
  FACEBOOK_SECRET: 
production:
  FACEBOOK_ID: 
  FACEBOOK_SECRET: 
MAILGUN_SMTP_LOGIN: 
MAILGUN_SMTP_PASSWORD: 